/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NovaChart: typeof import('./src/components/NovaChart/index.vue')['default']
    NovaLayout: typeof import('./src/components/NovaLayout/index.vue')['default']
    NovaTable: typeof import('./src/components/NovaTable/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScaleScreen: typeof import('./src/components/ScaleScreen/index.vue')['default']
  }
}
